### ISSUE TITLE
RedundantDependencyVersionsRule false positive

### ISSUE THREAD

**Issue by Stephan202** [lewisd32/lint-maven-plugin#15]
Running `mvn lint:check` on the POM below yields the following:

    [INFO] --- lint-maven-plugin:0.0.8:check (default-cli) @ example ---
     WARN [RedundantDependencyVersionsRule:81] 2013-10-28 13:48:35,050 - java.lang.IllegalStateException: Found 2 objects using path dependencies[groupId='com.lewisd' and artifactId='lint-maven-plugin' and type='jar']
     WARN [RedundantDependencyVersionsRule:81] 2013-10-28 13:48:35,054 - java.lang.IllegalStateException: Found 2 objects using path dependencyManagement/dependencies[groupId='com.lewisd' and artifactId='lint-maven-plugin' and type='jar']

Note that the POM is crafted to be a minimal example. The issue also occurs when the `dependencyManagement` section is in a parent POM (as it normally would be).

    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

        <modelVersion>4.0.0</modelVersion>

        <groupId>com.example</groupId>
        <artifactId>example</artifactId>
        <version>1.0-SNAPSHOT</version>

        <dependencyManagement>
            <dependencies>
                <dependency>
                    <groupId>com.lewisd</groupId>
                    <artifactId>lint-maven-plugin</artifactId>
                    <version>0.0.8</version>
                </dependency>
                <dependency>
                    <groupId>com.lewisd</groupId>
                    <artifactId>lint-maven-plugin</artifactId>
                    <version>0.0.8</version>
                    <classifier>javadoc</classifier>
                </dependency>
            </dependencies>
        </dependencyManagement>

        <dependencies>
            <dependency>
                <groupId>com.lewisd</groupId>
                <artifactId>lint-maven-plugin</artifactId>
            </dependency>
            <dependency>
                <groupId>com.lewisd</groupId>
                <artifactId>lint-maven-plugin</artifactId>
                <classifier>javadoc</classifier>
            </dependency>
        </dependencies>

        <build>
            <plugins>
                <plugin>
                    <groupId>com.lewisd</groupId>
                    <artifactId>lint-maven-plugin</artifactId>
                    <version>0.0.8</version>
                    <executions>
                        <execution>
                            <id>validate-pom</id>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <rules>
                            <excludes>
                                <exclude>OSS*</exclude>
                            </excludes>
                        </rules>
                    </configuration>
                </plugin>
            </plugins>
        </build>

    </project>

**Comment by Stephan202** [comment]
With #19 merged, we can close this issue now, correct? :)

**Comment by lewisd32** [comment]
Yep!
