### ISSUE TITLE
The examples in README.md should contain an execution ID

### ISSUE THREAD

**Issue by ddossot** [lewisd32/lint-maven-plugin#21]
Otherwise the plugin is not happy with its own config :wink:

**Comment by lkwg82** [comment]
Would be happy to see a pull request as I dont see what you mean.

Thx in advanced, for the issue and the pr. ☺

**Comment by ddossot** [comment]
Try the configuration shown in step 2. Your build will break because it doesn't contain an execution ID, which violates the `ExecutionId` rule.

**Comment by lkwg82** [comment]
My question was actually, what prevents you from 'press editing' on the `Readme.md` and fix it? :)

Discussing this issue may be helpful for the awareness but one has to do it finally.

**Comment by ddossot** [comment]
Awesome question.

Before forking the project and submitting a pull request, I wanted to make sure that this proposal for correction was valid and was not related to my lack of understanding about how the plug-in works.

As a rule of thumb, I assume that a README is accurate and that if it didn't work for me, it's probably because of an error on my side.

I'll wait for a maintainer of this project to confirm that the README is indeed inaccurate. If that is the case, then I'll be happy to fork the project and submit a pull request.

Thank you.

**Comment by lewisd32** [comment]
Hey folks :)

I think it's definitely a good idea for any pom samples in the README of this project to pass the lint check, otherwise it's setting people up for confusion (as this conversation has nicely demonstrated :smile:)

If someone wants to fix it up, I'll happily accept a PR.

Cheers!

**Comment by lewisd32** [comment]
Merged! Thanks again.
